### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by Haoyue-zhi** [yang1206/uniapp-template#127]
![Uploading 截屏2024-06-21 17.57.59.png…]()

**Comment by Haoyue-zhi** [comment]
![Uploading 截屏2024-06-21 17.57.59.png…]()

**Comment by Haoyue-zhi** [comment]
> uniapp-vite-template@0.0.1 dev:h5 /Users/zuowudanao/Desktop/uniapp-template
> cross-env VITE_MODE=development uni

请注意运行模式下，因日志输出、sourcemap 以及未压缩源码等原因，性能和包体积，均不及发行模式。
vite是按需编译，运行时点击某个未编译页面会先编译后加载，导致显示较慢，发行后无此问题。
node:fs:448
    return binding.readFileUtf8(path, stringToFlags(options.flag));
                   ^

Error: ENOENT: no such file or directory, open '/Users/zuowudanao/Desktop/uniapp-template/src/manifest.json'
    at Object.readFileSync (node:fs:448:20)
    at parseManifestJson (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/@dcloudio+uni-cli-shared@3.0.0-alpha-4010420240429001_@vueuse+core@9.13.0_vue@3.4.21_typescri_2mpvjdl3lhmmyyeavcxukacgoi/node_modules/@dcloudio/uni-cli-shared/dist/json/manifest.js:13:47)
    at /Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/@dcloudio+uni-shared@3.0.0-alpha-4010420240429001/node_modules/@dcloudio/uni-shared/dist/uni-shared.cjs.js:504:22
    at initUVueEnv (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/@dcloudio+vite-plugin-uni@3.0.0-alpha-4010420240429001_@vueuse+core@9.13.0_vue@3.4.21_typescr_lhbl6fi7fbdzanwlt73vz37kqm/node_modules/@dcloudio/vite-plugin-uni/dist/cli/uvue.js:16:69)
    at initEnv (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/@dcloudio+vite-plugin-uni@3.0.0-alpha-4010420240429001_@vueuse+core@9.13.0_vue@3.4.21_typescr_lhbl6fi7fbdzanwlt73vz37kqm/node_modules/@dcloudio/vite-plugin-uni/dist/cli/utils.js:144:28)
    at CAC.runDev (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/@dcloudio+vite-plugin-uni@3.0.0-alpha-4010420240429001_@vueuse+core@9.13.0_vue@3.4.21_typescr_lhbl6fi7fbdzanwlt73vz37kqm/node_modules/@dcloudio/vite-plugin-uni/dist/cli/action.js:49:25)
    at CAC.runMatchedCommand (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/cac@6.7.9/node_modules/cac/dist/index.js:614:34)
    at CAC.parse (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/cac@6.7.9/node_modules/cac/dist/index.js:541:12)
    at Object.<anonymous> (/Users/zuowudanao/Desktop/uniapp-template/node_modules/.pnpm/@dcloudio+vite-plugin-uni@3.0.0-alpha-4010420240429001_@vueuse+core@9.13.0_vue@3.4.21_typescr_lhbl6fi7fbdzanwlt73vz37kqm/node_modules/@dcloudio/vite-plugin-uni/dist/cli/index.js:57:5)
    at Module._compile (node:internal/modules/cjs/loader:1358:14) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/zuowudanao/Desktop/uniapp-template/src/manifest.json'
}

Node.js v20.14.0

**Comment by xchaoscn** [comment]
在src下新建一个manifest.json，里面写{}，再pnpm dev:h5 试试

**Comment by gradyll** [comment]
你这方法好像没有用

**Comment by Haoyue-zhi** [comment]
来试试我的脚本,把脚本复制到根目录下然后运行一下
[bootstrap.sh.zip](https://github.com/user-attachments/files/17340399/bootstrap.sh.zip)

**Comment by gradyll** [comment]
ok 了，应该是 @uni-helper/vite-plugin-uni-manifest 插件没有把manifest.config.ts打包出来变成 manifest.json

**Comment by nanfb** [comment]
> ok 了，应该是 @uni-helper/vite-plugin-uni-manifest 插件没有把manifest.config.ts打包出来变成 manifest.json

最后怎么解决的

**Comment by Haoyue-zhi** [comment]
> > ok 了，应该是 @uni-helper/vite-plugin-uni-manifest 插件没有把manifest.config.ts打包出来变成 manifest.json
> 
> 最后怎么解决的

新建一个uniapp项目把里面的manifest.json复制到你项目里就行了

**Comment by nanfb** [comment]
> > > ok 了，应该是 @uni-helper/vite-plugin-uni-manifest 插件没有把manifest.config.ts打包出来变成 manifest.json
> > 
> > 
> > 最后怎么解决的
> 
> 新建一个uniapp项目把里面的manifest.json复制到你项目里就行了

thanks

**Comment by yang1206** [comment]
不好意思，后续我会将manifest.json添加到提交中
